apiVersion: apps/v1
kind: Deployment      # Kubernetes resource kind we are creating
metadata:
  name: githubactions-aks
spec:
  selector:
    matchLabels:
      app: githubactions-aks
  replicas: 1                     # Number of replicas that will be created for this deployment
  template:
    metadata:
      labels:
        app: githubactions-aks
    spec:
      containers:
        - name: githubactions-aks
          image: ltimacrdemo.azurecr.io/githubaction-repo:latest       
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080 
