apiVersion: v1  
kind: Service 
metadata: 
  name: githubactions-aks-service 
spec:
  selector:
    app: githubactions-aks
  ports:
    - protocol: "TCP"
      port: 8080
       
  type: LoadBalancer 
