
name: Java CI with Maven
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
      id-token: write
      contents: read
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven cloud
      run:  mvn -B verify sonar:sonar -Dsonar.projectKey=sonarcloud-org2024 -Dsonar.organization=sonarcloud-org2024 -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=$SONARCLOUD_TOKEN
      env:
        GIT_HUB_TOKEN: ${{ secrets.GIT_HUB_TOKEN }}
        SONARCLOUD_TOKEN: ${{ secrets.SONARCLOUD_TOKEN }}
    - name: Build with Maven
      run: mvn -B install --file pom.xml
    - uses: actions/upload-artifact@v4
      with:
        name: Artifacts
        path: target/*.jar
    
    - uses: Azure/docker-login@v1
      with:
        login-server: ltimacrdemo.azurecr.io       
        username: ${{ secrets.REGISTRY_USERNAME }}      
        password: ${{ secrets.REGISTRY_PASSWORD }}       
          
    - run: |
         docker build . -t ltimacrdemo.azurecr.io/githubaction-repo:latest
         docker push ltimacrdemo.azurecr.io/githubaction-repo:latest

   

    # Set the target AKS cluster.
    - uses: azure/login@v2
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
        
  
    - uses: azure/aks-set-context@v3
      with:
          resource-group: Dev-Rg
          cluster-name: dev-aks
          creds: ${{ secrets.AZURE_CREDENTIALS }}
   
    - uses: Azure/k8s-create-secret@v1.1
      with:
         container-registry-url: ltimacrdemo.azurecr.io
         container-registry-username: ${{ secrets.REGISTRY_USERNAME }}
         container-registry-password: ${{ secrets.REGISTRY_PASSWORD }}
         secret-name: githubaction-aks-secret

    - uses: Azure/k8s-deploy@v4
      with:
          action: deploy
          manifests: |
             manifests/deployment.yml
             manifests/service.yml
          images: |
             devacrdemo123.azurecr.io/githubaction-repo:latest
          imagepullsecrets: |
             githubaction-aks-secret
