
name: Java CI with Maven
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
      id-token: write
      contents: read
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn -B install --file pom.xml
    - uses: actions/upload-artifact@v4
      with:
        name: Artifacts
        path: target/*.jar
    
    - uses: Azure/docker-login@v1
      with:
        login-server: ltimacrdemo.azurecr.io        #ltimacrdemo.azurecr.io
        username: ${{ secrets.REGISTRY_USERNAME }}      #LTIMacrdemo 
        password: ${{ secrets.REGISTRY_PASSWORD }}       #PtYZhec7Ph0P9tB/5d8R+VFfWVKmzTE0DZRvUTCWjL+ACRCqGTlR 
          
    - run: |
         docker build . -t ltimacrdemo.azurecr.io/githubaction-repo:latest
         docker push ltimacrdemo.azurecr.io/githubaction-repo:latest

   

         # Set the target AKS cluster.
    # - uses: azure/login@v1
    #   with:
    #       client-id: ${{ secrets.AZURE_CLIENT_ID }}
    #       tenant-id: ${{ secrets.AZURE_TENANT_ID }}
    #       subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
    #       enable-AzPSSession: true
    - name: Azure CLI script
      uses: azure/CLI@v1
      with:
          azcliversion: latest
          inlineScript: |
            az login --service-principal -u 1d457f67-8c31-452e-87b0-cbfdc4e04fa0 -p WIe8Q~OB5RsDtaZHbulRnOUbW7u.GwuPCo1STc3a --tenant f54e126c-2135-47cf-9d04-3b65e9abcaac

    # - uses: azure/aks-set-context@v3
    #   with:
    #       resource-group: Dev-Rg
    #       cluster-name: dev-aks
    - name: Azure CLI script
      uses: azure/CLI@v1
      with:
          azcliversion: latest
          inlineScript: |
             az aks get-credentials --resource-group Dev-Rg --name dev-aks kubelogin convert-kubeconfig -l azurecli

    - uses: Azure/k8s-create-secret@v1.1
      with:
         container-registry-url: ltimacrdemo.azurecr.io
         container-registry-username: ${{ secrets.REGISTRY_USERNAME }}
         container-registry-password: ${{ secrets.REGISTRY_PASSWORD }}
         secret-name: githubaction-aks-secret

    - uses: Azure/k8s-deploy@v4
      with:
          action: deploy
          manifests: |
             manifests/deployment.yml
             manifests/service.yml
          images: |
             devacrdemo123.azurecr.io/githubaction-repo:latest
          imagepullsecrets: |
             githubaction-aks-secret
